# Generated by Django 2.1.2 on 2018-10-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='caption',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='education',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
