# Generated by Django 2.1.2 on 2018-10-31 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181031_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.CharField(default=2, max_length=120),
            preserve_default=False,
        ),
    ]
