# Generated by Django 2.1.2 on 2018-10-31 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='skills',
        ),
    ]
