# Generated by Django 2.1.2 on 2018-10-20 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='persons',
            field=models.ManyToManyField(to='pages.Person'),
        ),
    ]
